version: "3"
services:
  directus:
    image: directus-node18:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
      - ./datahive-core:/directus/extensions/directus-extension-datahive/node_modules/datahive-core
    #  - ./datahive-core:/directus/node_modules/datahive-core
    # - ./database:/directus/database
    environment:
      KEY: "6288b48a-35cf-483d-8ebd-13c09118566e"
      SECRET: "5b96b8be-5c38-4129-a5f5-de7e8230c3fe"
      ADMIN_EMAIL: "jbmanillier@gmail.com"
      ADMIN_PASSWORD: "jBm765931!x"
      DB_CLIENT: "pg"
      DB_HOST: "ec2-34-242-154-118.eu-west-1.compute.amazonaws.com"
      DB_PORT: 5432
      DB_DATABASE: "d8drmsinnudf00"
      DB_USER: "nsrgsilqrgmapr"
      DB_PASSWORD: "c3c83bf16985c065b0be0a1d277d544cd764b61f78944ada4017020fa4294a5e"
      DB_SSL__REJECT_UNAUTHORIZED: "false"
      DIRECTUS_API_BASE_URL: "http://0.0.0.0:8055"
      DIRECTUS_API_TOKEN: "mYYPJypxN5ecLk2bxz-kztKpL_8oinXT"
      EXTENSIONS_AUTO_RELOAD : "true"